sonar.projectKey=ycea_qa-system
sonar.organization=ycea
sonar.projectName=QA System

# Что сканировать
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests

# Исключения
sonar.exclusions=backend/vendor/**,backend/storage/**,backend/bootstrap/cache/**,frontend/node_modules/**,frontend/dist/**,frontend/src/assets/**,**/*.test.ts,**/*.test.tsx,**/*.png,**/*.svg,**/*.ico

# Coverage от Pest
sonar.php.coverage.reportPaths=backend/coverage/cobertura.xml

# Кодировка
sonar.sourceEncoding=UTF-8
sonar.verbose=true