sonar.projectKey=ycea_qa-system
sonar.organization=ycea
sonar.projectName=QA System

# Что сканировать
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.exclusions=backend/vendor/**,backend/storage/**,backend/bootstrap/cache/**,frontend/node_modules/**,frontend/dist/**,**/*.test.ts,**/*.test.tsx

# Языки
sonar.language=php,javascript,typescript

# Coverage от Pest
sonar.php.coverage.reportPaths=backend/coverage/cobertura.xml